//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helsinki1952.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("helsinki1952.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 atletika kalapacsvetes	
        ///1 1 uszas 400m_gyorsuszas
        ///1 1 birkozas kotott_fogas_legsuly
        ///1 1 torna talajtorna
        ///1 1 torna felemas_korlat
        ///1 1 vivas kardvivas_egyeni
        ///1 1 okolvivas nagyvaltosuly
        ///1 1 uszas 200m_melluszas
        ///1 1 birkozas kotott_fogas_valtosuly
        ///1 1 uszas 100m_gyorsuszas
        ///1 1 sportloveszet onmukodo_sportpisztoly
        ///1 15 labdarugas ferfi_csapat
        ///1 3 ottusa ferfi_csapat
        ///1 6 vivas kardvivas_csapat
        ///1 5 uszas 4x100m_gyorsuszo_valto
        ///1 13 vizilabda ferfi_csapat
        ///2 1 ottusa ottusa_egyeni
        ///2 1 vivas to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Forrás {
            get {
                return ResourceManager.GetString("Forrás", resourceCulture);
            }
        }
    }
}
